import 'package:get/get.dart';

class LanguageString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'email_exist': 'Email Already Exist',
      'welcome_to': 'Welcome to',
      'ryze': ' Ryze',
      'signup_cont': 'SignUp to Continue',
      'signin_cont': 'SignIn to Continue',
      'login': 'LOGIN',
      'signup': 'SIGNUP',
      'email_address': 'Email Address',
      'enter_email_pl': 'Please enter email',
      'enter_valid_email': 'Please enter valid email',
      'password': 'Password',
      'password_must_exit': 'Please enter password',
      'name': 'Name',
      'enter_name_pl': 'Please enter your name',
      'digit_pass': 'Password must contain digit',
      'length_pass': 'Password must be at least 8 character',
      'cPassword': 'Confirm Password',
      'pass_identical': 'The password must be identical',
      'network_fail': 'No network connected',
      'ago': ' ago',
      'create_post': 'Create Post',
      'what_your_mind': 'What\'s on your mind?',
      '': '',
    },
    'ar_EG': {
      'email_exist': 'الايميل موجود بالفعل',
      'welcome_to': 'مرحبا بك فى تطبيق',
      'ryze': ' رايز',
      'signup_cont': 'انشئ حساب للمتابعه',
      'signin_cont': 'تسجيل الدخول للمتابعه',
      'login': 'دخول',
      'signup': 'انشاء حساب',
      'email_address': 'البريد الالكتروني',
      'enter_email_pl': 'من فضلك ادخل البريد الالكتروني',
      'enter_valid_email': 'من فضلك ادخل بريد صالح',
      'password': 'كلمه السر',
      'password_must_exit': 'من فضلك ادخل كلمه السر',
      'name': 'الاسم',
      'enter_name_pl': 'من فضلك ادخل اسمك',
      'digit_pass': 'يجب ان تحتوي كلمه السر على ارقام',
      'length_pass': 'يجب الا تقل كلمه السر عن 8 حروف',
      'cPassword': 'تاكيد كلمه السر',
      'pass_identical': 'يجب ان تكون كلمه السر متطابقه',
      'network_fail': 'لا يوجد اتصال بالانترنت',
      'ago': 'منذ ',
      'create_post': 'انشاء منشور',
      'what_your_mind': 'بم تفكر ؟',
    }
  };
}
